### ISSUE TITLE
Remote Redis Host Issue

### ISSUE THREAD

**Issue by mlrlite** [Rocketseat/adonis-bull#12] opened 2020-01-10 18:31 UTC
I've setup my docker container and set my redis connection to the connection below
`  kubernetes: {
    host: Env.get('REDIS_HOST', '127.0.0.1'),
    port: Env.get('REDIS_PORT', 6379),
    password: Env.get('REDIS_PASSWORD', null),
    db: Env.get('REDIS_DB', 6),
  }`
but each time I run the code it trys to connect to 127.0.0.1.

After some debugging, I was able to get it work by changing 
`this.config = redis[connection]`
to 
`this.config = {redis: redis[connection]}`

It seems like the Bull Queue is looking for a redis key with a config in the documentation example below.  The current code is only passing the config without the redis key, so it's causing me connection issues.  
`var audioQueue = new Queue('audio transcoding', {redis: {port: 6379, host: '127.0.0.1', password: 'foobared'}}); // Specify Redis connection using object`

Can you validate this so I can put in a PR to fix?

**Comment by 2peter3** [comment] 2020-01-11 03:24
Duplicate of #11 

PR is already submitted :)

**Comment by HigoRibeiro** [comment] 2020-01-13 13:01
It was fixed in #11

**Closed by HigoRibeiro** 2020-01-13 13:01 UTC
